
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author leoca
 */
public class CadastroTela extends javax.swing.JFrame {

    /**
     * Creates new form CadastroTela
     */
    public CadastroTela() {
        super("JavaHangman");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NicknameCadastroTextField = new javax.swing.JTextField();
        PerguntaCadastroTextField = new javax.swing.JTextField();
        PSenhaLabel = new javax.swing.JLabel();
        CadastrarButton = new javax.swing.JButton();
        VoltarCadastroButton = new javax.swing.JButton();
        SenhaCadastroPasswordField = new javax.swing.JPasswordField();
        NicknameLabel = new javax.swing.JLabel();
        SenhaLabel = new javax.swing.JLabel();
        PerguntaPessoalLabel = new javax.swing.JLabel();
        BackgroundCLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        NicknameCadastroTextField.setBackground(new java.awt.Color(51, 102, 255));
        NicknameCadastroTextField.setForeground(new java.awt.Color(255, 255, 255));
        NicknameCadastroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NicknameCadastroTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NicknameCadastroTextField);
        NicknameCadastroTextField.setBounds(460, 170, 200, 60);

        PerguntaCadastroTextField.setBackground(new java.awt.Color(51, 102, 255));
        PerguntaCadastroTextField.setForeground(new java.awt.Color(255, 255, 255));
        PerguntaCadastroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerguntaCadastroTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PerguntaCadastroTextField);
        PerguntaCadastroTextField.setBounds(460, 370, 200, 58);

        PSenhaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/perguntajg.png"))); // NOI18N
        getContentPane().add(PSenhaLabel);
        PSenhaLabel.setBounds(320, 440, 500, 23);

        CadastrarButton.setBackground(new java.awt.Color(51, 102, 255));
        CadastrarButton.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarButton.setText("Cadastrar");
        CadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarButton);
        CadastrarButton.setBounds(570, 470, 100, 40);

        VoltarCadastroButton.setBackground(new java.awt.Color(51, 102, 255));
        VoltarCadastroButton.setForeground(new java.awt.Color(255, 255, 255));
        VoltarCadastroButton.setText("Voltar");
        VoltarCadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarCadastroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarCadastroButton);
        VoltarCadastroButton.setBounds(460, 470, 100, 40);

        SenhaCadastroPasswordField.setBackground(new java.awt.Color(51, 102, 255));
        SenhaCadastroPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        SenhaCadastroPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaCadastroPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(SenhaCadastroPasswordField);
        SenhaCadastroPasswordField.setBounds(460, 270, 200, 60);

        NicknameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/nickname.png"))); // NOI18N
        getContentPane().add(NicknameLabel);
        NicknameLabel.setBounds(460, 140, 100, 16);

        SenhaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/senha.png"))); // NOI18N
        getContentPane().add(SenhaLabel);
        SenhaLabel.setBounds(460, 240, 60, 20);

        PerguntaPessoalLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/perguntapessal.png"))); // NOI18N
        getContentPane().add(PerguntaPessoalLabel);
        PerguntaPessoalLabel.setBounds(460, 340, 210, 21);

        BackgroundCLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        getContentPane().add(BackgroundCLabel);
        BackgroundCLabel.setBounds(-600, -190, 1940, 940);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NicknameCadastroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NicknameCadastroTextFieldActionPerformed
 
    }//GEN-LAST:event_NicknameCadastroTextFieldActionPerformed

    private void SenhaCadastroPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaCadastroPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaCadastroPasswordFieldActionPerformed

    private void CadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarButtonActionPerformed
        String nickname = NicknameCadastroTextField.getText();
        String senha = new String (SenhaCadastroPasswordField.getPassword());
        String perguntaPessoal = PerguntaCadastroTextField.getText();
        Usuario u = new Usuario();
        u.setNickname(nickname);
        u.setSenha(senha);
        u.setPerguntaPessoal(perguntaPessoal);
        try{
        u.inserir();
        CadastroLoginTela clt = new CadastroLoginTela();
        clt.setVisible(true);
        this.dispose();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_CadastrarButtonActionPerformed

    private void PerguntaCadastroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerguntaCadastroTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerguntaCadastroTextFieldActionPerformed

    private void VoltarCadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarCadastroButtonActionPerformed
      CadastroLoginTela clt = new CadastroLoginTela();
      clt.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_VoltarCadastroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundCLabel;
    private javax.swing.JButton CadastrarButton;
    private javax.swing.JTextField NicknameCadastroTextField;
    private javax.swing.JLabel NicknameLabel;
    private javax.swing.JLabel PSenhaLabel;
    private javax.swing.JTextField PerguntaCadastroTextField;
    private javax.swing.JLabel PerguntaPessoalLabel;
    private javax.swing.JPasswordField SenhaCadastroPasswordField;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JButton VoltarCadastroButton;
    // End of variables declaration//GEN-END:variables
}
