
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author leoca
 */
public class ContinuarJogoTela extends javax.swing.JFrame {

    /**
     * Creates new form ContinuarJogoTela
     */
    public static ContinuarJogoTela Instance;
    public JLabel lblr;
    public JLabel lblr2;
    public ContinuarJogoTela() {
        super("JavaHangman");
        initComponents();
        Instance = this;
        lblr = idRecordeLabel;
        lblr.setVisible(false);
        lblr2 = ptJogLabel;
        lblr2.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        idRecordeLabel = new javax.swing.JLabel();
        ptJogLabel = new javax.swing.JLabel();
        txtContSalvarLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 230, 110, 40);

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salvar e sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 230, 110, 40);
        getContentPane().add(idRecordeLabel);
        idRecordeLabel.setBounds(520, 160, 52, 31);
        getContentPane().add(ptJogLabel);
        ptJogLabel.setBounds(333, 74, 47, 0);

        txtContSalvarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/contSalva.png"))); // NOI18N
        getContentPane().add(txtContSalvarLabel);
        txtContSalvarLabel.setBounds(80, 30, 640, 26);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        backgroundLabel.setPreferredSize(new java.awt.Dimension(800, 400));
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(-220, -10, 1160, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     JogoTela jogo = new JogoTela ();
     jogo.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     String idJog = idRecordeLabel.getText();
     String ptJog = ptJogLabel.getText();
     int idJogador = Integer.parseInt(idJog);
     int pontuacao = Integer.parseInt(ptJog);
     Pontuacao pt = new Pontuacao (pontuacao, idJogador);
     String r = pt.listarRecorde();
     if ("".equals(r)){
         pt.inserirRecorde();
     }
     else{
         if (pontuacao > Integer.parseInt(r)){
             pt.alterarRecorde();
         }
         
     }
     this.dispose();
     CadastroLoginTela clt = new CadastroLoginTela();
     clt.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContinuarJogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContinuarJogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContinuarJogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContinuarJogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContinuarJogoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel idRecordeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel ptJogLabel;
    private javax.swing.JLabel txtContSalvarLabel;
    // End of variables declaration//GEN-END:variables
}
