
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author leoca
 */
public class JogoTela extends javax.swing.JFrame {

    /**
     * Creates new form JogoTela
     */
    public static JogoTela Instance;
    public JLabel lblr1;
    private Jogo jogo;
    public JogoTela() {
        super("JavaHangman");
        initComponents();
        Instance = this;
        lblr1 = idRecordeLabel;
        lblr1.setVisible(false);
        this.setLocationRelativeTo(null);
        forca1Label.setVisible(false);
        forca2Label.setVisible(false);
        forca3Label.setVisible(false);
        forca4Label.setVisible(false);
        forca5Label.setVisible(false);
        forca6Label.setVisible(false);
        jogo = new Jogo ();
        jogo.iniciarJogo();
        PalavraEscondidaLabel.setText(jogo.getPalavraEscondida().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ForcaTextField = new javax.swing.JTextField();
        DigiteLPLabel = new javax.swing.JLabel();
        PalavraEscondidaLabel = new javax.swing.JLabel();
        EnviarButton = new javax.swing.JButton();
        forca1Label = new javax.swing.JLabel();
        forca2Label = new javax.swing.JLabel();
        forca3Label = new javax.swing.JLabel();
        forca4Label = new javax.swing.JLabel();
        forca5Label = new javax.swing.JLabel();
        forca6Label = new javax.swing.JLabel();
        idRecordeLabel = new javax.swing.JLabel();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        ForcaTextField.setBackground(new java.awt.Color(51, 51, 255));
        ForcaTextField.setForeground(new java.awt.Color(255, 255, 255));
        ForcaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ForcaTextField.setPreferredSize(new java.awt.Dimension(250, 50));
        ForcaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForcaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ForcaTextField);
        ForcaTextField.setBounds(110, 210, 250, 50);

        DigiteLPLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/DigitarLetra.png"))); // NOI18N
        getContentPane().add(DigiteLPLabel);
        DigiteLPLabel.setBounds(110, 140, 460, 50);

        PalavraEscondidaLabel.setBackground(new java.awt.Color(51, 102, 255));
        PalavraEscondidaLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PalavraEscondidaLabel);
        PalavraEscondidaLabel.setBounds(120, 310, 240, 30);

        EnviarButton.setBackground(new java.awt.Color(51, 102, 255));
        EnviarButton.setForeground(new java.awt.Color(255, 255, 255));
        EnviarButton.setText("Enviar");
        EnviarButton.setToolTipText("");
        EnviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EnviarButton);
        EnviarButton.setBounds(200, 270, 75, 23);

        forca1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/forca_1.png"))); // NOI18N
        getContentPane().add(forca1Label);
        forca1Label.setBounds(730, 440, 137, 207);

        forca2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/forca_2.png"))); // NOI18N
        getContentPane().add(forca2Label);
        forca2Label.setBounds(730, 460, 139, 206);

        forca3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/forca_3.png"))); // NOI18N
        getContentPane().add(forca3Label);
        forca3Label.setBounds(730, 450, 139, 206);

        forca4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/forca_4.png"))); // NOI18N
        getContentPane().add(forca4Label);
        forca4Label.setBounds(730, 470, 150, 170);

        forca5Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/forca_5.png"))); // NOI18N
        getContentPane().add(forca5Label);
        forca5Label.setBounds(740, 470, 140, 170);

        forca6Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/forca_6.png"))); // NOI18N
        getContentPane().add(forca6Label);
        forca6Label.setBounds(730, 470, 139, 160);
        getContentPane().add(idRecordeLabel);
        idRecordeLabel.setBounds(1220, 10, 37, 16);

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        BackgroundLabel.setMaximumSize(new java.awt.Dimension(1280, 720));
        BackgroundLabel.setMinimumSize(new java.awt.Dimension(1280, 720));
        BackgroundLabel.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(BackgroundLabel);
        BackgroundLabel.setBounds(-130, -140, 1870, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ForcaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForcaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ForcaTextFieldActionPerformed

    private void EnviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarButtonActionPerformed
        String forcaTexto = ForcaTextField.getText();
        if (forcaTexto.isEmpty()){
            return;
        }
        jogo.verificarLetra(forcaTexto);
        PalavraEscondidaLabel.setText(jogo.getPalavraEscondida().toString());
        int tentativas = jogo.getTentativas();      
    switch (tentativas) {
        case 1:
            forca1Label.setVisible(true);
            break;
        case 2:
            forca1Label.setVisible(false);
            forca2Label.setVisible(true);
            break;
        case 3:
            forca2Label.setVisible(false);
            forca3Label.setVisible(true);
            break;
        case 4:
            forca3Label.setVisible(false);
            forca4Label.setVisible(true);
            break;
        case 5:
            forca4Label.setVisible(false);
            forca5Label.setVisible(true);
            break;
        case 6:
            forca5Label.setVisible(false);
            forca6Label.setVisible(true);
            break;
    }
     ForcaTextField.setText("");
        if (jogo.jogadorAcertou() || tentativas == 6) {
        int palavrasAcertadas = jogo.getPalavrasAcertadas();
        ContinuarJogoTela cjt = new ContinuarJogoTela ();
        String idrecorde = idRecordeLabel.getText();
        ContinuarJogoTela.Instance.lblr.setText(idrecorde);
        String palavrasCertas = Integer.toString(palavrasAcertadas);
        ContinuarJogoTela.Instance.lblr2.setText(palavrasCertas);
        cjt.setVisible(true);
        this.dispose();  
        }
    }//GEN-LAST:event_EnviarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel DigiteLPLabel;
    private javax.swing.JButton EnviarButton;
    private javax.swing.JTextField ForcaTextField;
    private javax.swing.JLabel PalavraEscondidaLabel;
    private javax.swing.JLabel forca1Label;
    private javax.swing.JLabel forca2Label;
    private javax.swing.JLabel forca3Label;
    private javax.swing.JLabel forca4Label;
    private javax.swing.JLabel forca5Label;
    private javax.swing.JLabel forca6Label;
    private javax.swing.JLabel idRecordeLabel;
    // End of variables declaration//GEN-END:variables
}
