
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author leoca
 */
public class MenuTela extends javax.swing.JFrame {

    public static MenuTela Instance;
    public JLabel lblr;
    /**
     * Creates new form MenuTela
     */
    public MenuTela() {
        super("JavaHangman");
        initComponents();
        Instance = this;
        lblr = IdRecordeLabel;
        lblr.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JogarButton = new javax.swing.JButton();
        RecordeButton = new javax.swing.JButton();
        SairMenuButton = new javax.swing.JButton();
        IdRecordeLabel = new javax.swing.JLabel();
        JHLabel = new javax.swing.JLabel();
        BackgroundMLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        JogarButton.setBackground(new java.awt.Color(51, 102, 255));
        JogarButton.setForeground(new java.awt.Color(255, 255, 255));
        JogarButton.setText("Jogar");
        JogarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JogarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(JogarButton);
        JogarButton.setBounds(500, 250, 150, 50);

        RecordeButton.setBackground(new java.awt.Color(51, 102, 255));
        RecordeButton.setForeground(new java.awt.Color(255, 255, 255));
        RecordeButton.setText("Recorde");
        RecordeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RecordeButton);
        RecordeButton.setBounds(500, 320, 150, 50);

        SairMenuButton.setBackground(new java.awt.Color(51, 102, 255));
        SairMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        SairMenuButton.setText("Sair");
        SairMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SairMenuButton);
        SairMenuButton.setBounds(500, 390, 150, 50);
        getContentPane().add(IdRecordeLabel);
        IdRecordeLabel.setBounds(10, 20, 22, 16);

        JHLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/javahangmantxt.png"))); // NOI18N
        getContentPane().add(JHLabel);
        JHLabel.setBounds(380, 40, 400, 70);

        BackgroundMLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        BackgroundMLabel.setMaximumSize(new java.awt.Dimension(1280, 720));
        BackgroundMLabel.setMinimumSize(new java.awt.Dimension(1280, 720));
        BackgroundMLabel.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(BackgroundMLabel);
        BackgroundMLabel.setBounds(-360, -120, 2010, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JogarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JogarButtonActionPerformed
     JogoTela jogoTela = new JogoTela();
     String nickname = lblr.getText();
     Usuario u = new Usuario (nickname, null, null);
     int idJogador = u.pegarId();
     String idRecorde = (Integer.toString(idJogador));
     JogoTela.Instance.lblr1.setText(idRecorde);
     jogoTela.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_JogarButtonActionPerformed

    private void SairMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairMenuButtonActionPerformed
       this.dispose();
    }//GEN-LAST:event_SairMenuButtonActionPerformed

    private void RecordeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordeButtonActionPerformed
        String nickname = lblr.getText();
        Usuario u = new Usuario (nickname, null, null);
        int idJogador = u.pegarId();
        Pontuacao pt = new Pontuacao (idJogador);
        String recorde = pt.listarRecorde();
        JOptionPane.showMessageDialog(null, "seu recorde é de " + recorde + " pontos");
    }//GEN-LAST:event_RecordeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundMLabel;
    private javax.swing.JLabel IdRecordeLabel;
    private javax.swing.JLabel JHLabel;
    private javax.swing.JButton JogarButton;
    private javax.swing.JButton RecordeButton;
    private javax.swing.JButton SairMenuButton;
    // End of variables declaration//GEN-END:variables
}
