
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 23.01328-0
 */
public class PerguntaPessoalTela extends javax.swing.JFrame {

    /**
     * Creates new form RecuperacaoSenhaTela
     */
    public PerguntaPessoalTela() {
        super("JavaHangman");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PerguntaPessoalRecSenhaTextField = new javax.swing.JTextField();
        ProximoPerguntaPessoalButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NicknamePerguntaTextField = new javax.swing.JTextField();
        nicknameLabel = new javax.swing.JLabel();
        perguntapessoalLabel = new javax.swing.JLabel();
        recsenhaLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 400));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        PerguntaPessoalRecSenhaTextField.setBackground(new java.awt.Color(51, 102, 255));
        PerguntaPessoalRecSenhaTextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PerguntaPessoalRecSenhaTextField);
        PerguntaPessoalRecSenhaTextField.setBounds(290, 240, 200, 56);

        ProximoPerguntaPessoalButton.setBackground(new java.awt.Color(51, 102, 255));
        ProximoPerguntaPessoalButton.setForeground(new java.awt.Color(255, 255, 255));
        ProximoPerguntaPessoalButton.setText("Próximo");
        ProximoPerguntaPessoalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProximoPerguntaPessoalButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ProximoPerguntaPessoalButton);
        ProximoPerguntaPessoalButton.setBounds(400, 310, 100, 40);

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 310, 100, 40);

        NicknamePerguntaTextField.setBackground(new java.awt.Color(51, 102, 255));
        NicknamePerguntaTextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(NicknamePerguntaTextField);
        NicknamePerguntaTextField.setBounds(290, 150, 200, 59);

        nicknameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/nickname.png"))); // NOI18N
        getContentPane().add(nicknameLabel);
        nicknameLabel.setBounds(290, 120, 100, 30);

        perguntapessoalLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/perguntapessal.png"))); // NOI18N
        getContentPane().add(perguntapessoalLabel);
        perguntapessoalLabel.setBounds(290, 210, 220, 30);

        recsenhaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/recsebga.png"))); // NOI18N
        getContentPane().add(recsenhaLabel);
        recsenhaLabel.setBounds(220, 20, 360, 35);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        backgroundLabel.setMaximumSize(new java.awt.Dimension(800, 400));
        backgroundLabel.setMinimumSize(new java.awt.Dimension(800, 400));
        backgroundLabel.setPreferredSize(new java.awt.Dimension(800, 400));
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(-13, -14, 1010, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProximoPerguntaPessoalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProximoPerguntaPessoalButtonActionPerformed
    String login = NicknamePerguntaTextField.getText();
    String pergunta = PerguntaPessoalRecSenhaTextField.getText();
    try {
        Usuario usuario = new Usuario (login, null, pergunta);
        DAO DAO = new DAO();
        if(DAO.recuperarUsuario(usuario)) {
            RecuperacaoSenhaTela rst = new RecuperacaoSenhaTela();
            RecuperacaoSenhaTela.Instance.lbl.setText(login);
            rst.setVisible(true);
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(null, "nickname ou time incorretos");
        }
    }
    catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_ProximoPerguntaPessoalButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginTela lt = new LoginTela();
        lt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerguntaPessoalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerguntaPessoalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerguntaPessoalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerguntaPessoalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerguntaPessoalTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NicknamePerguntaTextField;
    private javax.swing.JTextField PerguntaPessoalRecSenhaTextField;
    private javax.swing.JButton ProximoPerguntaPessoalButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JLabel perguntapessoalLabel;
    private javax.swing.JLabel recsenhaLabel;
    // End of variables declaration//GEN-END:variables
}
