
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 23.01328-0
 */
public class RecuperacaoSenhaTela extends javax.swing.JFrame {
    
    
    public static RecuperacaoSenhaTela Instance;
    public JLabel lbl;
    /**
     * Creates new form RecuperacaoSenhaTela
     */
    public RecuperacaoSenhaTela() {
        super("JavaHangman");
        initComponents();
        Instance = this;
        lbl = nicknameRecuperarSenhaLabel;
        lbl.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        novaSenhaPasswordField = new javax.swing.JPasswordField();
        nicknameRecuperarSenhaLabel = new javax.swing.JLabel();
        novasnheaabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Alterar Senha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 220, 110, 40);

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 220, 110, 40);

        novaSenhaPasswordField.setBackground(new java.awt.Color(51, 102, 255));
        novaSenhaPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(novaSenhaPasswordField);
        novaSenhaPasswordField.setBounds(280, 150, 200, 62);
        getContentPane().add(nicknameRecuperarSenhaLabel);
        nicknameRecuperarSenhaLabel.setBounds(0, 0, 0, 0);

        novasnheaabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novasenha.png"))); // NOI18N
        getContentPane().add(novasnheaabel);
        novasnheaabel.setBounds(280, 120, 160, 30);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(-280, -20, 1350, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CadastroLoginTela clt = new CadastroLoginTela();
        clt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String login = lbl.getText();
        String novaSenha = new String (novaSenhaPasswordField.getPassword());
        try {
        Usuario usuario = new Usuario (login, novaSenha, null);
        DAO DAO = new DAO();
        if(DAO.alteraSenha(usuario)) {
           Usuario u = new Usuario();
            u.setNickname(login);
            u.setSenha(novaSenha);
            try {
            u.alterarSenha();
            CadastroLoginTela clt = new CadastroLoginTela();
            clt.setVisible(true);
            this.dispose();
            }
            catch(Exception e){
           e.printStackTrace();
            } 
        }
        else {
            JOptionPane.showMessageDialog(null, "nickname incorreto");
        }
    }
    catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperacaoSenhaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperacaoSenhaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperacaoSenhaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperacaoSenhaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperacaoSenhaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel nicknameRecuperarSenhaLabel;
    private javax.swing.JPasswordField novaSenhaPasswordField;
    private javax.swing.JLabel novasnheaabel;
    // End of variables declaration//GEN-END:variables
}
